version: 2.1

executors:
  default:
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m

orbs:
  codecov: codecov/codecov@1.0.5
  android: circleci/android@0.1.0

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "buildSrc/src/main/java/dependencies/Versions.kt" }}-{{ checksum "buildSrc/src/main/java/dependencies/Deps.kt" }}
            - gradle-cache-{{ checksum "buildSrc/src/main/java/dependencies/Versions.kt" }}-

  save_gradle_cache:
    steps:
      - save_cache:
          key: gradle-cache-{{ checksum "buildSrc/src/main/java/dependencies/Versions.kt" }}-{{ checksum "buildSrc/src/main/java/dependencies/Deps.kt" }}
          paths:
            - ~/.gradle

jobs:
  unit_test:
    executor: default
    parameters:
      run-on-master:
        type: boolean
        default: false
    steps:
      - checkout
      - restore_gradle_cache
      - android/restore-build-cache
      - run:
          name: Run unit tests
          command: ./gradlew jacocoTestReport --stacktrace
      - codecov/upload
      - android/save-build-cache
      - when:
          condition: << parameters.run-on-master >>
          steps:
            - save_gradle_cache
  publish:
    executor: default
    steps:
      - checkout
      - restore_gradle_cache
      - android/restore-build-cache
      - run:
          name: Prepare artifacts
          command: ./gradlew publishToMavenLocal --stacktrace
      - run:
          name: Upload to Bintray
          command: ./gradlew bintrayUpload --stacktrace
workflows:
  version: 2
  test:
    jobs:
      - unit_test:
          run-on-master: true
          filters:
            branches:
              only: master
      - unit_test:
          run-on-master: false
          filters:
            branches:
              ignore: master
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

